"
" WINDOWS Vim settings
" type :echo $HOME 
" in Vim to find where this file is pathed to on your system
" may vary from 32/64 bit and should be found with that method
"
set autoindent                  " automatic indent new lines
set smartindent                 " smart indent true
set nowrap                      " no word wrap
set softtabstop=2
set shiftwidth=2                " 2 space indents
set tabstop=2                   " 2 space tabs
set expandtab                   " spaces for tabs
set nosmarttab                  " no smarttabs true
set ruler                       " show the cursor position all the time
set number                      " line numbers
set showmatch                   " brackets/braces
set mouse=a                     " allow mouse in terminal
set guifont=Consolas:h11        " font
set list                        " draw line breaks
set backspace=indent,eol,start  " map backspace key in windows
colorscheme desert              " so far my favorite
syntax on                       " syntax highlighting
set smartcase                   " lowercase searches are auto case insensitive
set clipboard=unnamed           " use the clipboard on copy/cut
